export type LearningPathKind="Academic"|"International"|"Vocational"|"Practical";
export type LearningPath={id:string;name:string;kind:LearningPathKind;description:string;levels:string[];subjects:string[];modes:("Online"|"In person"|"Self-paced")[];sourceLabel:string;sourceUrl?:string};
export const LEARNING_PATHS:LearningPath[]=[
{id:"psle",name:"PSLE",kind:"Academic",description:"Primary-school examination preparation and subject support.",levels:["Primary"],subjects:["Mathematics","Setswana","English","Social Studies","Science","Agriculture","Religious and Moral Education"],modes:["Online","In person","Self-paced"],sourceLabel:"Botswana Examinations Council"},
{id:"bgcse",name:"BGCSE",kind:"Academic",description:"Botswana senior-secondary learning and examination support across core, science, humanities, business, creative and technical subjects.",levels:["Senior Secondary"],subjects:["English Language","Setswana","Mathematics","Science","Chemistry","Physics","Biology","History","Geography","Social Studies","Computer Studies","Commerce","Accounting","Business Studies","Agriculture","Design & Technology","Food & Nutrition","Fashion & Fabric","Hospitality & Tourism Studies"],modes:["Online","In person","Self-paced"],sourceLabel:"Botswana Examinations Council"},
{id:"igcse",name:"Cambridge IGCSE",kind:"International",description:"Flexible international secondary study across a broad choice of subjects.",levels:["Secondary","14–16"],subjects:["Mathematics","English","Sciences","Business","Humanities","Languages","Computer Science","Creative and technical subjects"],modes:["Online","In person","Self-paced"],sourceLabel:"Cambridge International"},
{id:"trades",name:"Trades & Vocational Skills",kind:"Vocational",description:"Practical pathways such as auto mechanics, electrical installation, welding, plumbing, carpentry and other vocational skills.",levels:["Skills Training","Certificate"],subjects:["Auto Mechanics","Electrical Installation","Welding & Fabrication","Plumbing & Pipe Fitting","Carpentry & Joinery","Bricklaying & Plastering","Refrigeration & Air Conditioning","Machine Fitting","Panel Beating & Spray Painting","Horticulture","Agriculture","Dress Making"],modes:["Online","In person"],sourceLabel:"Government of Botswana"},
{id:"apprenticeships",name:"Apprenticeships",kind:"Vocational",description:"Find learning and work pathways where practical training, a sponsoring organisation and formal requirements matter.",levels:["Apprenticeship"],subjects:["Trade apprenticeship","On-the-job learning","Workplace skills"],modes:["In person"],sourceLabel:"Government of Botswana"},
{id:"driving",name:"Driving School & Road Skills",kind:"Practical",description:"A practical learning category for driving instruction, road knowledge and preparation. Providers must supply their own verified scope and credentials.",levels:["Beginner","Learner","Licence preparation"],subjects:["Driving","Road rules","Vehicle control","Road safety"],modes:["In person"],sourceLabel:"TutorMe category"}];
export function getLearningPath(id:string){return LEARNING_PATHS.find(p=>p.id===id);}
