import Link from "next/link";

const pillars=[
 ["01","FIND SUPPORT","Tutors, tuition centres and academic-support providers in one place.","/find"],
 ["02","POST A NEED","Tell us the subject, level and goal. You do not need to know who to contact yet.","/enrol"],
 ["03","KEEP LEARNING","Useful study moves, resources and verified updates give families a reason to return.","/feed"]
];

export default function Home(){return <main>
<header className="siteHeader"><Link href="/" className="brand"><span className="brandMark">T</span><span><strong>TutorMe</strong><small>ACADEMIC SUPPORT</small></span></Link><nav><Link href="/find">Find support</Link><Link href="/feed">Study</Link><Link href="/resources">Resources</Link><Link href="/enrol">Post a need</Link></nav></header>
<section className="hero marketHomeHero"><div className="heroCopy"><span className="eyebrow">Academic support · Botswana</span><h1>Find the right<br/><em>support to learn.</em></h1><p>TutorMe is being built as a simpler way for students and families to discover tutors, tuition centres and academic support — starting with a real tuition centre in Gaborone.</p><div className="actions"><Link className="button primary" href="/find">Find academic support</Link><Link className="button ghost" href="/enrol">Post a need</Link></div><div className="homeTrust"><span>✓ Direct enquiry</span><span>✓ Verified listings</span><span>✓ Mobile-first</span></div></div><div className="heroVisual marketplaceVisual"><div className="visualOrbit"><div><span>Maths</span><strong>Find</strong><small>what fits</small></div><i>+</i><div><span>Gaborone</span><strong>Compare</strong><small>your options</small></div><i>+</i><div><span>Student</span><strong>Start</strong><small>learning</small></div></div></div></section>
<section className="section homeIntro"><div className="sectionHead"><span className="eyebrow">The idea</span><h2>One place to start when you need academic help.</h2><p>The long-term goal is a useful tutoring network: more choice for families, better discovery for tutors and centres, and a trusted path from “I need help” to the right conversation.</p></div><div className="featureGrid">{pillars.map(([n,t,d,h])=><Link className="feature featureLink" href={h} key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><b>Open →</b></Link>)}</div></section>
<section className="marketSignal"><div className="marketSignalInner"><div><span className="eyebrow">Built around the learner</span><h2>Choice without the chaos.</h2><p>Good discovery should help a family make a confident next decision without turning a student into a public profile or forcing them through a complicated system.</p></div><div className="signalSteps"><div><b>01</b><span>What do you need?</span></div><div><b>02</b><span>What options fit?</span></div><div><b>03</b><span>Who should you contact?</span></div></div></div></section>
<section className="section currentOffer"><div className="sectionHead"><span className="eyebrow">Start local</span><h2>TutorMe itself is already real.</h2><p>Before the wider network grows, families can use the existing TutorMe tuition centre in Block 8, Gaborone.</p></div><div className="offerCard"><div><span className="tag">Verified TutorMe listing</span><h3>TutorMe Tuition Center</h3><p>Private academic tuition for primary, secondary and tertiary students.</p><div className="chips"><span>Block 8</span><span>In person</span><span>Study support</span></div></div><div><strong>P5,500</strong><small>per student · tuition included</small><a className="button primary" href="https://wa.me/26772281640">WhatsApp Ruth</a><Link className="button ghost" href="/find/tutorme-centre">View listing</Link></div></div></section>
<section className="studyBand"><div><span className="eyebrow">A reason to return</span><h2>Find help.<br/>Then keep learning.</h2><p>Short study moves, retrieval challenges, useful resources and verified updates keep TutorMe more useful between conversations.</p></div><Link className="button light" href="/feed">See today&apos;s study moves →</Link></section>
<footer><div><strong>TutorMe</strong><span>Under Keza Educational / Keza Tutoring</span></div><span>Block 8, Gaborone, Botswana</span></footer>
</main>}