import Link from "next/link";

const strengths=[
  ["🎓","Private tuition","Focused academic support shaped around what the student needs help with."],
  ["🧭","Primary to tertiary","Tell Ruth the student’s level, subjects and goals so the right tuition conversation can start."],
  ["📝","Study support","Practical study guidance, retrieval prompts and useful resources give students a reason to return."],
  ["📍","Block 8, Gaborone","A local tuition option for families who want direct contact rather than a marketplace search."],
  ["📚","Learning resources","A growing library of approved study material and short learning moves."],
  ["💬","Talk to Ruth","Call or WhatsApp directly when you are ready to ask about tuition and enrolment."]
];

export default function Home(){return <main>
<header className="siteHeader"><Link href="/" className="brand"><span className="brandMark">T</span><span><strong>TutorMe</strong><small>KEZA TUTORING</small></span></Link><nav><Link href="/feed">Study</Link><Link href="/resources">Resources</Link><Link href="/enrol">Enrol</Link><Link href="/admin">Operations</Link></nav></header>
<section className="hero"><div className="heroCopy"><span className="eyebrow">Block 8 · Gaborone · Botswana</span><h1>Better support.<br/><em>Better study.</em></h1><p>TutorMe provides private academic tuition for primary, secondary and tertiary students, with a simple digital companion for students and parents.</p><div className="actions"><Link className="button primary" href="/enrol">Enrol / enquire</Link><a className="button ghost" href="https://wa.me/26772281640">WhatsApp Ruth</a></div><p className="truth">P5,500 per student, including tuition services.</p></div><div className="heroVisual"><div className="visualCard"><span>✦</span><strong>TutorMe</strong><small>Private academic tuition</small><b>Block 8, Gaborone</b></div></div></section>
<section className="section"><div className="sectionHead"><span className="eyebrow">For families</span><h2>Start with the student, not a complicated system.</h2><p>Parents and students should be able to understand the offer, decide whether TutorMe is a fit, and reach a real person quickly.</p></div><div className="featureGrid">{strengths.map(([i,t,d])=><article className="feature" key={t}><span>{i}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="studyBand"><div><span className="eyebrow">A reason to return</span><h2>Study → practise → reflect → come back.</h2><p>Short study moves, retrieval challenges and practical parent guidance keep the digital side connected to the real tuition experience.</p></div><Link className="button light" href="/feed">See today&apos;s study moves</Link></section>
<section className="section"><div className="sectionHead"><span className="eyebrow">How it starts</span><h2>Three simple steps.</h2></div><div className="featureGrid"><article className="feature"><span>01</span><h3>Tell us what is needed</h3><p>Share the student&apos;s level, subjects and the kind of academic help you are looking for.</p></article><article className="feature"><span>02</span><h3>Talk to Ruth</h3><p>TutorMe reviews the enquiry and follows up directly about the appropriate tuition arrangement.</p></article><article className="feature"><span>03</span><h3>Start learning</h3><p>Once the arrangement is agreed, the student can focus on the work that matters.</p></article></div></section>
<section className="section package"><div><span className="eyebrow">TutorMe package</span><h2>P5,500<br/><small>per student</small></h2><p>Tuition services included. Contact Ruth for enrolment details and the right arrangement for the student.</p></div><div className="packageCard"><strong>Enrol With Ruth</strong><span>Call / WhatsApp</span><a href="tel:+26772281640">+267 72281640</a><a className="button primary" href="https://wa.me/26772281640">WhatsApp Ruth</a><Link className="button ghost" href="/enrol">Start an enquiry</Link></div></section>
<footer><div><strong>TutorMe</strong><span>Under Keza Educational / Keza Tutoring</span></div><span>Block 8, Gaborone, Botswana</span></footer></main>}
