import type { Provider } from "@/lib/firebase/data";

export const providerSeed: Provider[] = [
  {
    id: "tutorme-centre",
    kind: "Tuition Centre",
    name: "TutorMe Tuition Center",
    tagline: "Private academic tuition in Block 8.",
    description: "The current TutorMe centre offering private academic tuition for primary, secondary and tertiary students in Block 8, Gaborone.",
    location: "Block 8, Gaborone",
    modes: ["In person"],
    subjects: ["Academic tuition", "Study support", "Exam preparation"],
    levels: ["Primary", "Secondary", "Tertiary"],
    verified: true,
    featured: true,
    contactLabel: "Talk to Ruth",
    phone: "+267 72281640",
    priceLabel: "P5,500 per student",
    published: true,
    createdAt: "2026-10-07T00:00:00Z",
    updatedAt: "2026-10-07T00:00:00Z",
  },
  {
    id: "preview-math",
    kind: "Tutor",
    name: "Preview Mathematics Tutor",
    tagline: "A sample tutor listing for the marketplace preview.",
    description: "Demo data showing how an individual tutor could present subjects, levels, delivery options and a clear next step.",
    location: "Gaborone",
    modes: ["In person", "Online"],
    subjects: ["Mathematics", "Statistics"],
    levels: ["Secondary", "Tertiary"],
    verified: false,
    featured: false,
    contactLabel: "Request contact",
    priceLabel: "Rate to be confirmed",
    published: true,
    createdAt: "2026-10-07T00:00:00Z",
    updatedAt: "2026-10-07T00:00:00Z",
  },
  {
    id: "preview-science",
    kind: "Tutor",
    name: "Preview Science Tutor",
    tagline: "A sample science specialist listing.",
    description: "Demo data showing a focused profile for learners looking for science support and exam preparation.",
    location: "Gaborone",
    modes: ["Online"],
    subjects: ["Biology", "Chemistry", "General Science"],
    levels: ["Secondary", "Tertiary"],
    verified: false,
    featured: false,
    contactLabel: "Request contact",
    priceLabel: "Rate to be confirmed",
    published: true,
    createdAt: "2026-10-07T00:00:00Z",
    updatedAt: "2026-10-07T00:00:00Z",
  },
  {
    id: "preview-study",
    kind: "Academic Support",
    name: "Preview Study Support",
    tagline: "A sample academic-support listing.",
    description: "Demo data for structured study support, revision planning and learning habits.",
    location: "Botswana",
    modes: ["Online"],
    subjects: ["Study skills", "Revision planning"],
    levels: ["Primary", "Secondary"],
    verified: false,
    featured: false,
    contactLabel: "Request support",
    priceLabel: "Details to be confirmed",
    published: true,
    createdAt: "2026-10-07T00:00:00Z",
    updatedAt: "2026-10-07T00:00:00Z",
  },
];
