"use client";
import{collection,deleteDoc,doc,getDoc,getDocs,limit,orderBy,query,setDoc,updateDoc,where}from"firebase/firestore";
import{auth,db}from"./client";
export type CentreRole="owner"|"staff"|"tutor"|"parent"|"student";
export type WorkspaceStatus="pending"|"active"|"paused";
export type SessionMode="In person"|"Online";
export type SessionStatus="Scheduled"|"Completed"|"Cancelled";
export type FeeStatus="Outstanding"|"Part paid"|"Paid"|"Waived";
export type CentreWorkspace={id:string;name:string;country:string;currency:string;timezone:string;ownerUid:string;contactName:string;contactPhone:string;location:string;description:string;status:WorkspaceStatus;providerId?:string;createdAt:string;updatedAt:string};
export type CentreMember={uid:string;email:string;displayName:string;role:CentreRole;studentIds:string[];status:"active"|"invited";joinedAt:string};
export type CentreStudent={id:string;name:string;educationLevel:string;subjects:string;parentUids:string[];status:"active"|"inactive";notes:string;createdAt:string;updatedAt:string};
export type TuitionSession={id:string;studentId:string;studentName:string;title:string;subject:string;tutorName:string;mode:SessionMode;scheduledAt:string;durationMinutes:number;meetingUrl:string;status:SessionStatus;notes:string;createdAt:string;updatedAt:string};
export type TuitionFee={id:string;studentId:string;studentName:string;description:string;amount:number;currency:string;dueDate:string;status:FeeStatus;paidAt:string;paymentNote:string;createdAt:string;updatedAt:string};
export type CentreInvite={id:string;orgId:string;studentId:string;studentName:string;role:"parent"|"student";email:string;status:"pending"|"claimed";createdAt:string;claimedBy:string;claimedAt:string};
const col=(orgId:string,name:string)=>collection(db,"centreWorkspaces",orgId,name);const now=()=>new Date().toISOString();function uid(){return auth.currentUser?.uid??""}
export async function getOwnedWorkspace(){const u=uid();if(!u)return null;const s=await getDocs(query(collection(db,"centreWorkspaces"),where("ownerUid","==",u),limit(1)));const d=s.docs[0];return d?({id:d.id,...d.data()} as CentreWorkspace):null}
export async function getWorkspace(orgId:string){const s=await getDoc(doc(db,"centreWorkspaces",orgId));return s.exists()?({id:s.id,...s.data()} as CentreWorkspace):null}
export async function createWorkspace(input:Omit<CentreWorkspace,"id"|"ownerUid"|"status"|"createdAt"|"updatedAt">){const u=uid();if(!u)throw new Error("Sign in first.");const ref=doc(collection(db,"centreWorkspaces"));const t=now();await setDoc(ref,{...input,ownerUid:u,status:"pending",createdAt:t,updatedAt:t});await setDoc(doc(db,"centreWorkspaces",ref.id,"members",u),{uid:u,email:auth.currentUser?.email??"",displayName:auth.currentUser?.displayName??input.contactName,role:"owner",studentIds:[],status:"active",joinedAt:t});return ref.id}
export async function getMembers(orgId:string){const s=await getDocs(query(col(orgId,"members"),orderBy("joinedAt","desc"),limit(200)));return s.docs.map(d=>d.data() as CentreMember)}
export async function saveStudent(orgId:string,input:Omit<CentreStudent,"id"|"createdAt"|"updatedAt">,id?:string){const t=now(),ref=id?doc(db,"centreWorkspaces",orgId,"students",id):doc(col(orgId,"students"));const data=id?{...input,updatedAt:t}:{...input,createdAt:t,updatedAt:t};await setDoc(ref,data,{merge:true});return ref.id}
export async function getStudents(orgId:string){const s=await getDocs(query(col(orgId,"students"),orderBy("createdAt","desc"),limit(500)));return s.docs.map(d=>({id:d.id,...d.data()} as CentreStudent))}
export async function saveSession(orgId:string,input:Omit<TuitionSession,"id"|"createdAt"|"updatedAt">,id?:string){const t=now(),ref=id?doc(db,"centreWorkspaces",orgId,"sessions",id):doc(col(orgId,"sessions"));const data=id?{...input,updatedAt:t}:{...input,createdAt:t,updatedAt:t};await setDoc(ref,data,{merge:true});return ref.id}
export async function getSessions(orgId:string){const s=await getDocs(query(col(orgId,"sessions"),orderBy("scheduledAt","desc"),limit(500)));return s.docs.map(d=>({id:d.id,...d.data()} as TuitionSession))}
export async function saveFee(orgId:string,input:Omit<TuitionFee,"id"|"createdAt"|"updatedAt">,id?:string){const t=now(),ref=id?doc(db,"centreWorkspaces",orgId,"fees",id):doc(col(orgId,"fees"));const data=id?{...input,updatedAt:t}:{...input,createdAt:t,updatedAt:t};await setDoc(ref,data,{merge:true});return ref.id}
export async function getFees(orgId:string){const s=await getDocs(query(col(orgId,"fees"),orderBy("dueDate","asc"),limit(500)));return s.docs.map(d=>({id:d.id,...d.data()} as TuitionFee))}
export async function markFeePaid(orgId:string,id:string,note=""){await updateDoc(doc(db,"centreWorkspaces",orgId,"fees",id),{status:"Paid",paidAt:now(),paymentNote:note,updatedAt:now()})}
export async function createInvite(orgId:string,input:Omit<CentreInvite,"id"|"orgId"|"status"|"createdAt"|"claimedBy"|"claimedAt">){const ref=doc(col(orgId,"invites"));await setDoc(ref,{...input,orgId,status:"pending",createdAt:now(),claimedBy:"",claimedAt:""});return ref.id}
export async function getInvite(orgId:string,id:string){const s=await getDoc(doc(db,"centreWorkspaces",orgId,"invites",id));return s.exists()?({id:s.id,...s.data()} as CentreInvite):null}
export async function claimInvite(orgId:string,id:string){const u=auth.currentUser;if(!u)throw new Error("Sign in first.");const invite=await getInvite(orgId,id);if(!invite||invite.status!=="pending")throw new Error("This invitation is no longer available.");if(invite.email&&invite.email.toLowerCase()!==(u.email??"").toLowerCase())throw new Error("This invitation was issued to a different email address.");const t=now();await setDoc(doc(db,"centreWorkspaces",orgId,"members",u.uid),{uid:u.uid,email:u.email??"",displayName:u.displayName??invite.email,role:invite.role,studentIds:[invite.studentId],status:"active",joinedAt:t},{merge:true});const student=await getDoc(doc(db,"centreWorkspaces",orgId,"students",invite.studentId));if(student.exists()){const parents=Array.isArray(student.data().parentUids)?student.data().parentUids:[];if(!parents.includes(u.uid))await updateDoc(student.ref,{parentUids:[...parents,u.uid],updatedAt:t})}await updateDoc(doc(db,"centreWorkspaces",orgId,"invites",id),{status:"claimed",claimedBy:u.uid,claimedAt:t})}
