"use client";
import{useEffect,useState}from"react";
import{createUserWithEmailAndPassword,signInWithEmailAndPassword,onAuthStateChanged,type User}from"firebase/auth";
import{useParams,useRouter}from"next/navigation";
import Link from"next/link";
import{auth}from"@/lib/firebase/client";
import{getPublishedProviders,createConnectionRequest,type Provider}from"@/lib/firebase/data";
export default function ConnectCentre(){const{id}=useParams<{id:string}>();const router=useRouter();const[user,setUser]=useState<User|null>(null);const[provider,setProvider]=useState<Provider|null>(null);const[mode,setMode]=useState<"create"|"signin">("create");const[form,setForm]=useState({name:"",email:"",password:"",role:"parent" as "parent"|"student",message:""});const[error,setError]=useState("");const[done,setDone]=useState(false);
useEffect(()=>onAuthStateChanged(auth,setUser),[]);
useEffect(()=>{getPublishedProviders().then(ps=>setProvider(ps.find(p=>p.id===id)||null)).catch(e=>setError(e instanceof Error?e.message:"Could not load centre."))},[id]);
async function submit(e:React.FormEvent){e.preventDefault();setError("");try{let u=user;if(!u){const cred=mode==="create"?await createUserWithEmailAndPassword(auth,form.email,form.password):await signInWithEmailAndPassword(auth,form.email,form.password);u=cred.user}if(!provider||!u)throw new Error("Centre or account unavailable.");await createConnectionRequest({workspaceId:provider.workspaceId||provider.id,providerId:provider.id,requesterUid:u.uid,requesterName:form.name||u.displayName||"TutorMe member",requesterEmail:u.email||form.email,role:form.role,message:form.message});setDone(true)}catch(e){setError(e instanceof Error?e.message:"Could not send request.")}}
if(!provider)return <main className="simplePage"><div className="simpleCard"><h1>Centre not found.</h1><Link className="button primary" href="/find">Back to support</Link></div></main>;
return <main className="simplePage"><div className="simpleCard"><span className="eyebrow">Connect privately</span><h1>Ask {provider.name} to connect.</h1><p>Your request stays private and goes to the centre workspace for review.</p>{done?<><h2>Request sent.</h2><p>The centre can accept or decline the request from its TutorMe workspace.</p><Link className="button primary" href="/find">Back to support</Link></>:<form className="adminForm compact" onSubmit={submit}>{!user&&<><div className="tabs"><button type="button" className={mode==="create"?"active":""} onClick={()=>setMode("create")}>Create account</button><button type="button" className={mode==="signin"?"active":""} onClick={()=>setMode("signin")}>Sign in</button></div>{mode==="create"&&<input placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input type="password" minLength={6} placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></>}<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as "parent"|"student"})}><option value="parent">I am a parent/guardian</option><option value="student">I am a student</option></select><textarea placeholder="What would you like help with?" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} required/><button className="button primary">Send connection request</button>{error&&<p className="error">{error}</p>}</form>}</div></main>}